### ISSUE TITLE
On many Concurent Request the TLM Server sometimes crashes 

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#247]
Error Log:

```
automatic_walk-time_tables-awt-swiss-tml-api-1         | [ERROR] Error in "Index_NearestNeighbors_obj": IllegalStateException: readNode: failed reading the correct node type information
automatic_walk-time_tables-awt-swiss-tml-api-1         | [ERROR] Exception on /swiss_name [GET]
automatic_walk-time_tables-awt-swiss-tml-api-1         | Traceback (most recent call last):
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
automatic_walk-time_tables-awt-swiss-tml-api-1         |     response = self.full_dispatch_request()
automatic_walk-time_tables-awt-swiss-tml-api-1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
automatic_walk-time_tables-awt-swiss-tml-api-1         |     rv = self.handle_user_exception(e)
automatic_walk-time_tables-awt-swiss-tml-api-1         |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
automatic_walk-time_tables-awt-swiss-tml-api-1         |     return cors_after_request(app.make_response(f(*args, **kwargs)))
automatic_walk-time_tables-awt-swiss-tml-api-1         |                                                 ^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
automatic_walk-time_tables-awt-swiss-tml-api-1         |     rv = self.dispatch_request()
automatic_walk-time_tables-awt-swiss-tml-api-1         |          ^^^^^^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
automatic_walk-time_tables-awt-swiss-tml-api-1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
automatic_walk-time_tables-awt-swiss-tml-api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/app/app.py", line 91, in get_name
automatic_walk-time_tables-awt-swiss-tml-api-1         |     raise e
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/app/app.py", line 62, in get_name
automatic_walk-time_tables-awt-swiss-tml-api-1         |     swiss_names = name_index.get_names(lat, lon, 3)
automatic_walk-time_tables-awt-swiss-tml-api-1         |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/app/swiss_TML_api/name_finding/name_finder.py", line 43, in get_names
automatic_walk-time_tables-awt-swiss-tml-api-1         |     self.index.nearest((lat, lon, lat, lon), num_results=n, objects="raw")
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/rtree/index.py", line 1028, in nearest
automatic_walk-time_tables-awt-swiss-tml-api-1         |     return self._nearest_obj(coordinates, num_results, objects)
automatic_walk-time_tables-awt-swiss-tml-api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/rtree/index.py", line 956, in _nearest_obj
automatic_walk-time_tables-awt-swiss-tml-api-1         |     core.rt.Index_NearestNeighbors_obj(
automatic_walk-time_tables-awt-swiss-tml-api-1         |   File "/usr/local/lib/python3.11/site-packages/rtree/core.py", line 13, in check_return
automatic_walk-time_tables-awt-swiss-tml-api-1         |     raise RTreeError(msg)
automatic_walk-time_tables-awt-swiss-tml-api-1         | rtree.exceptions.RTreeError: Error in "Index_NearestNeighbors_obj": IllegalStateException: readNode: failed reading the correct node type information

**Comment by wp99cp** [comment]
related with #383 ?
